---
- name: Install OpenJDK
  yum:
    name:
    - "java-{{ open_jdk_version }}-openjdk"
    - maven
  when: ansible_distribution == 'Centos'

- name: Install OpenJDK
  apt:
    name:
    - "openjdk-{{ openjdkversion }}-jdk"
    - maven
  when: ansible_distribution == 'Ubuntu'